/// T110: WeeklyReview domain entity — pure Dart, no Flutter imports.

enum PatternConfidence { high, medium, low }

final class ReviewPattern {
  const ReviewPattern({required this.description, required this.confidence});

  final String description;
  final PatternConfidence confidence;

  Map<String, dynamic> toJson() => {
    'description': description,
    'confidence': confidence.name,
  };

  factory ReviewPattern.fromJson(Map<String, dynamic> j) => ReviewPattern(
    description: j['description'] as String,
    confidence: PatternConfidence.values.byName(
      j['confidence'] as String? ?? 'medium',
    ),
  );
}

final class ReviewInsight {
  const ReviewInsight({required this.description, required this.action});

  final String description;
  final String action;

  Map<String, dynamic> toJson() => {
    'description': description,
    'action': action,
  };

  factory ReviewInsight.fromJson(Map<String, dynamic> j) => ReviewInsight(
    description: j['description'] as String,
    action: j['action'] as String? ?? '',
  );
}

final class PartnerReviewSummary {
  const PartnerReviewSummary({
    required this.partnerName,
    required this.topStreaks,
    required this.sharedWins,
  });

  final String partnerName;

  /// List of {habit, days} maps.
  final List<Map<String, dynamic>> topStreaks;
  final List<String> sharedWins;

  factory PartnerReviewSummary.fromJson(Map<String, dynamic> j) =>
      PartnerReviewSummary(
        partnerName: j['partner_name'] as String? ?? '',
        topStreaks:
            (j['top_streaks'] as List?)?.cast<Map<String, dynamic>>() ?? [],
        sharedWins: (j['shared_wins'] as List?)?.cast<String>() ?? [],
      );
}

final class WeeklyReview {
  const WeeklyReview({
    required this.id,
    required this.userId,
    required this.weekStart,
    required this.weekEnd,
    required this.patterns,
    required this.insights,
    this.partnerSummary,
    required this.summaryText,
    required this.expiresAt,
    required this.createdAt,
  });

  final String id;
  final String userId;
  final DateTime weekStart;
  final DateTime weekEnd;
  final List<ReviewPattern> patterns;
  final List<ReviewInsight> insights;

  /// Null when the user has no active partner.
  final PartnerReviewSummary? partnerSummary;

  /// Plain-text narrative summary generated by the AI.
  final String summaryText;

  /// Expires 90 days after creation; review is removed from history after this.
  final DateTime expiresAt;
  final DateTime createdAt;

  bool get isExpired => DateTime.now().isAfter(expiresAt);

  @override
  bool operator ==(Object other) =>
      identical(this, other) || (other is WeeklyReview && other.id == id);

  @override
  int get hashCode => id.hashCode;
}
